config/routes.rb
Pots::Application.routes.draw do
  devise_for :users

  get "display/index"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  resources :attachments

  resources :categories

  resources :vendors

  resources :prices

  resources :project_line_items

  resources :projects

  resources :products

   root :to => "pages#home"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :product
	
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.xml
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.xml
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.xml
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.xml
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to(@attachment, :notice => 'Attachment was successfully created.') }
        format.xml  { render :xml => @attachment, :status => :created, :location => @attachment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attachment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.xml
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to(@attachment, :notice => 'Attachment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attachment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.xml
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to(attachments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to image_tag("show.png"), @attachment %> |
<%= link_to image_tag("back.png"), attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<%= link_to image_tag("home.png"), pages_home_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Product</th>
    <th>Link</th>
    <th>Tags</th>
    <th>Note</th>
    <th></th>
    <th><%= link_to image_tag("new.png"), new_attachment_path %></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= attachment.title %></td>
    <td><%= attachment.product_id %></td>
    <td><%= attachment.link %></td>
    <td><%= attachment.tags %></td>
    <td><%= attachment.note %></td>
    <td><%= link_to image_tag("show.png"), attachment %></td>
    <td><%= link_to image_tag("edit.png"), edit_attachment_path(attachment) %></td>
    <td><%= link_to image_tag("delete.png"), attachment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag("new.png"), new_attachment_path %>
<%= link_to image_tag("home.png"), pages_home_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to image_tag("back.png"), attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @attachment.title %>
</p>

<p>
  <b>Product:</b>
  <%= @attachment.product_id %>
</p>

<p>
  <b>Link:</b>
  <%= @attachment.link %>
</p>

<p>
  <b>Tags:</b>
  <%= @attachment.tags %>
</p>

<p>
  <b>Note:</b>
  <%= @attachment.note %>
</p>


<%= link_to image_tag("edit.png"), edit_attachment_path(@attachment) %> |
<%= link_to image_tag("back.png"), attachments_path %>