config/routes.rb
Pots::Application.routes.draw do
  devise_for :users

  get "display/index"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  resources :attachments

  resources :categories

  resources :vendors

  resources :prices

  resources :project_line_items

  resources :projects

  resources :products

   root :to => "pages#home"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :product
	
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	

		
end

app/models/price.rb
class Price < ActiveRecord::Base
	belongs_to :product
	belongs_to :vendor
	
	validates :product_id, :vendor_id, :quote_price, :presence => true
	validates :quote_price, :numericality => {:greater_than_or_equal_to => 0.01}
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :vendor
	has_many :prices
	has_many :project_line_items
	has_many :attachments
	
	validates :description, :category_id, :presence => true
	before_destroy :ensure_not_referenced_by_project_line_item
	
	def ensure_not_referenced_by_project_line_item
		if project_line_items.count.zero?
			return true
		else
			error[:base] << "Product Line Items present"
			return false
		end
	end

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_line_items, :dependent => :destroy
	
	validates :title, :presence => true
	validates :title, :uniqueness => true
	
end

app/models/project_line_item.rb
class ProjectLineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :project
	
	validates :product_id, :project_id, :quantity, :presence => true
	validates :quantity, :numericality => {:greater_than_or_equal_to => 0.01}
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :products
	has_many :prices
	
	validates :company_name, :presence => true
	validates :company_name, :uniqueness => true
	
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
	helper_method :sort_column, :sort_direction
	
  def index
  	@title = "Product Listing"
  	@products = Product.order(sort_column + " " + sort_direction) # tweaked
  end
  
  private
  
  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  # GET /prices
  # GET /prices.xml
  def index
    @prices = Price.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prices }
    end
  end

  # GET /prices/1
  # GET /prices/1.xml
  def show
    @price = Price.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @price }
    end
  end

  # GET /prices/new
  # GET /prices/new.xml
  def new
    @price = Price.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @price }
    end
  end

  # GET /prices/1/edit
  def edit
    @price = Price.find(params[:id])
  end

  # POST /prices
  # POST /prices.xml
  def create
    @price = Price.new(params[:price])

    respond_to do |format|
      if @price.save
        format.html { redirect_to(@price, :notice => 'Price was successfully created.') }
        format.xml  { render :xml => @price, :status => :created, :location => @price }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prices/1
  # PUT /prices/1.xml
  def update
    @price = Price.find(params[:id])

    respond_to do |format|
      if @price.update_attributes(params[:price])
        format.html { redirect_to(@price, :notice => 'Price was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.xml
  def destroy
    @price = Price.find(params[:id])
    @price.destroy

    respond_to do |format|
      format.html { redirect_to(prices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
  def sortable(column, title = nil)
    title ||= column.titleize
  	css_class = column == sort_column ? "current #{sort_direction}" : nil
  	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  	link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>POTS | <%= @title %></title>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div is="user_nav">
		<% if user_signed_in? %>
		  Signed in as <%= current_user.email %>. Not you?
		  <%= link_to "Sign out", destroy_user_session_path %>
		<% else %>
		  <%= link_to "Sign in", new_user_session_path %>
		<% end %>
	</div>
		
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  Placeholder<br />
  <%= link_to image_tag("home.png"), pages_home_path %>
</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>
  Placeholder<br />
  <%= link_to image_tag("home.png"), pages_home_path %>
</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>
  <%= link_to "Manage Products", products_path %><br />
  <%= link_to "Manage Vendors", vendors_path %><br />
  <%= link_to "Manage Categories", categories_path %><br />
  <%= link_to "Manage Attachments", attachments_path %><br />
  <%= link_to "Manage Projects", projects_path %><br />
  <br />
  Manage Product Pricing<br />
  Work on a Project<br />
  <br />
  <%= link_to "Display", display_index_path %><br />
  <%= link_to "Price Index", prices_path %><br />    
  <%= link_to "Project Line Item Index", project_line_items_path %><br />
  <br />
  <br />
  <%= link_to "Contact Page", pages_contact_path %><br />
  <%= link_to "About Page", pages_about_path %><br />
  
</p>