config/routes.rb
Pots::Application.routes.draw do
  devise_for :users

  get "display/index"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  resources :attachments

  resources :categories

  resources :vendors

  resources :prices

  resources :project_line_items

  resources :projects

  resources :products

   root :to => "pages#home"

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_line_items, :dependent => :destroy
	
	validates :title, :presence => true
	validates :title, :uniqueness => true
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.text_field :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to image_tag("show.png"), @project %> |
<%= link_to image_tag("back.png"), projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<%= link_to image_tag("home.png"), pages_home_path %>

<table>
  <tr>
  	<th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th>Location</th>
    <th>Note</th>
    <th>Completed</th>
    <th></th>
    <th><%= link_to image_tag("new.png"), new_project_path %></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  	<td><%= project.id %></td>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= project.location %></td>
    <td><%= project.note %></td>
    <td><%= project.completed %></td>
    <td><%= link_to image_tag("show.png"), project %></td>
    <td><%= link_to image_tag("edit.png"), edit_project_path(project) %></td>
    <td><%= link_to image_tag("delete.png"), project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag("new.png"), new_project_path %>
<%= link_to image_tag("home.png"), pages_home_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to image_tag("back.png"), projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Location:</b>
  <%= @project.location %>
</p>

<p>
  <b>Note:</b>
  <%= @project.note %>
</p>

<p>
  <b>Completed:</b>
  <%= @project.completed %>
</p>


<%= link_to image_tag("edit.png"), edit_project_path(@project) %> |
<%= link_to image_tag("back.png"), projects_path %>