config/routes.rb
Pots::Application.routes.draw do
  devise_for :users

  get "display/index"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  resources :attachments

  resources :categories

  resources :vendors

  resources :prices

  resources :project_line_items

  resources :projects

  resources :products

   root :to => "pages#home"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	

		
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	helper_method :sort_column, :sort_direction
	
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.order(sort_column + " " + sort_direction) # tweaked

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to image_tag("show.png"), @category %> |
<%= link_to image_tag("back.png"), categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<%= link_to image_tag("home.png"), pages_home_path %>

<table class="pretty">
  <tr>
  	<th><%= link_to image_tag("new.png"), new_category_path %></th>
  	<th><%= sortable "id", "ID" %></th>
    <th><%= sortable "title" %></th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  	<td><%= link_to image_tag("show.png"), category %></td>
  	<td><%= category.id %></td>
    <td><%= category.title %></td>
    <td><%= category.description %></td>
    <td><%= link_to image_tag("edit.png"), edit_category_path(category) %></td>
    <td><%= link_to image_tag("delete.png"), category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag("new.png"), new_category_path %>
<%= link_to image_tag("home.png"), pages_home_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to image_tag("back.png"), categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>ID:</b>
  <%= @category.id %>
</p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to image_tag("edit.png"), edit_category_path(@category) %> |
<%= link_to image_tag("back.png"), categories_path %>